### PR TITLE
Foxy robot add

### PR DESCRIPTION
**Pull request by girvenavery2022**
This pull request adds in the package to launch on the physical ohm robot. The addition of this package will allow us to test the software on Ohm.

### CODE REVIEW

**Comment by andyblarblar** [comment]
Is this a copy of the nav from gazebo, or is it up to date with Mammoth?

**Comment by girvenavery2022** [comment]
Its the most recent copy of navigation from mammoth_snowplow foxy branch

**Review by dcutting133 — APPROVED** [review]

**Review by andyblarblar — APPROVED** [review]
Probobly best we merge this before testing tommarow to avoid messing with forks.

**Comment by girvenavery2022** [comment]
Most definitely, I'm just waiting on Jordan's approval before I merge it lol

**Review by JordanKra — APPROVED** [review]
Yeah we'll definitely need this for testing tomorrow so lets merge this

**Pull request merged**
